Dan/Areas/Admin/Controllers/ProductImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dan.Areas.Admin.Infrastuctures;
using Dan.Areas.Admin.View;
using Dan.Areas.Admin.View.Image;
using Dan.Infrastructures.Repository;
using Dan.Models.Image;

namespace Dan.Areas.Admin.Controllers
{
    public class ProductImageController : AbstractController
    {
        public override DeleteProcessResponse OnDeleteProcess(AdminUniversalDeleteView view)
        {
            throw new NotImplementedException();
        }

        // GET: Admin/Image
        public ActionResult Index()
        {
            using (var r = new ImageRepository())
            {
                return View(r.TakeEntities(null, false).ToList().AsShortAdminView());
            }
        }

        // GET: Admin/Image/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            using (var r = new ImageRepository())
            {
                var entity = r.TakeEntity(id.Value);
                if (entity == null)
                {
                    return RedirectToAction("Index");
                }
                return View(entity.AsLargeView());
            }
        }

        // GET: Admin/Image/Create
        public ActionResult Create(long? id)
        {
            using (var r1 = new ImageCategoryRepository())
            {
                var categories = r1.TakeEntityList(id);
                var view = new AdminCatalogImageCreateView
                {
                    CategoryId = id ?? 0,
                    CategorySelectList = categories
                };
                return View(view);
            }
        }

        // POST: Admin/Image/Create
        [HttpPost]
        public ActionResult Create(AdminCatalogImageCreateView view)
        {
            if (UploadImage(view) == UploadImageResponse.Successfully)
            {
                return RedirectToAction("Index");
            }
            return View(view);

            //using (var r1 = new ImageCategoryRepository())
            //{
            //    //===================================================================
            //    if (ModelState.IsValid == false)
            //    {
            //        view.CategorySelectList = r1.TakeEntityList(view.CategoryId);
            //        return View(view);
            //    }
            //
            //    //===================================================================
            //    if (view.CategoryId <= 0)
            //    {
            //        ModelState.AddModelError(nameof(view.CategoryId), "Категория не указана");
            //        view.CategorySelectList = r1.TakeEntityList(view.CategoryId);
            //        return View(view);
            //    }
            //
            //    if (r1.IsExistEntity(view.CategoryId) == false)
            //    {
            //        ModelState.AddModelError(nameof(view.CategoryId), "Категория не найдена");
            //        view.CategorySelectList = r1.TakeEntityList(view.CategoryId);
            //        return View(view);
            //    }
            //
            //    if (view.ImageFile.HasFile() == false)
            //    {
            //        ModelState.AddModelError(nameof(view.ImageFile), "Изображение не загружено");
            //        view.CategorySelectList = r1.TakeEntityList(view.CategoryId);
            //        return View(view);
            //    }
            //
            //
            //    //===================================================================
            //    using (var r2 = new ImageRepository(r1.Context))
            //    {
            //        ImageEntity entity = r2.Context.ImageEntities.Add(view.AsEntity());
            //        r2.SaveChanges();
            //
            //        view.ImageFile.SaveAs(Server.MapPath($"/Content/public/{entity.EntityId}_original.{view.FileType}"));
            //        view.ImageFile.SaveImageAs(Server.MapPath($"/Content/public/{entity.EntityId}_large.{view.FileType}"), new FileEditImagePropertyView { SaveImageFormat = view.FileType });
            //        view.ImageFile.SaveImageAs(Server.MapPath($"/Content/public/{entity.EntityId}_small.{view.FileType}"), new FileEditImagePropertyView(260, 160) { SaveImageFormat = view.FileType });
            //    }
            //
            //    return RedirectToAction("Index");
            //}
        }

        // GET: Admin/Image/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/Image/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Image/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Image/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Dan/Areas/Admin/Views/ProductImage/Create.cshtml
@model Dan.Areas.Admin.View.Image.AdminCatalogImageCreateView

@{
    ViewBag.Title = "Добавление нового изображения";
}

@Html.Partial("SectionHeader", "Добавление изображения")


@using (Html.BeginForm("Create", "ProductImage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="col-md-6">
        <div class="x_panel">
            <div class="x_title">
                <h2>
                    Основная информация
                </h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.CategoryId, Model.CategorySelectList, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" class="form-control" name=@nameof(Model.ImageFile) id=@nameof(Model.ImageFile) />
                            @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="x_panel">
            <div class="x_title">
                <h2>
                    SEO
                </h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    <div class="form-group">
                        @Html.LabelFor(model => model.AltAttribute, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.AltAttribute, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.AltAttribute, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TitleAttribute, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TitleAttribute, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TitleAttribute, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Добавить изображение" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Dan/Areas/Admin/Views/ProductImage/Index.cshtml
@model IEnumerable<Dan.Areas.Admin.View.Image.AdminCatalogImageShortView>

@{
    ViewBag.Title = "Index";
}
@Styles.Render("~/bundles/Admin/DataBase/Styles")
@Scripts.Render("~/bundles/Admin/DataBase/Scripts")

<div class="col-md-12 col-sm-12 col-xs-12" style="min-height: 630px;">
    <div class="x_panel">
        <div class="x_title">
            <h2>
                Изображения
                [ @Html.ActionLink("Добавить изображение", "Create") ]
            </h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">

            <table id="MatchesDataBase" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.EntityId)
                        </th>
                        <th>
                            Изображение
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TitleAttribute)

                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.AltAttribute)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.CategoryName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CreatedDate)
                        </th>
                    </tr>
                </thead>


                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.EntityId)
                            </td>
                            <td style="padding: 0; width: 120px;">
                                <img style="height: 120px; width:100%;" src="@item.FilePath" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TitleAttribute)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AltAttribute)
                            </td>
                            <td>
                                @Html.ActionLink(item.CategoryName, "Details", "ProductImageCategory", new {id = item.CategoryId}, new { title = "Перейти к категории" })
                            </td> 
                            <td>
                                @Html.DisplayFor(modelItem => item.CreatedDate)
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $('#MatchesDataBase').dataTable();
</script>