Dan/Models/Catalog/ManufactureEntity.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Web;
using Dan.Models.Image;
using Dan.Models.Interface;

namespace Dan.Models.Catalog
{
    public class ManufactureEntity 
        : IAbstractEntityInterface
        , IEntityWithImageInterface
    {
        public long EntityId { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }

        public SeoEntityType Seo { get; set; }


        public long ImageId { get; set; }
        public virtual ImageEntity ImagEntity { get; set; }
        public virtual List<ProductEntity> ProductEntities { get; set; } = new List<ProductEntity>();

        public class Configuration : EntityTypeConfiguration<ManufactureEntity>
        {
            public Configuration()
            {
                HasKey(i => i.EntityId);
                ToTable("catalog.ManufactureEntity");

                //=================================================================
                HasMany(p => p.ProductEntities).WithRequired(p => p.ManufactureEntity).HasForeignKey(p => p.ManufactureId).WillCascadeOnDelete(true);

                //=================================================================
                Property(p => p.Name).IsRequired().HasMaxLength(128);
                Property(p => p.ShortDescription).IsRequired().HasMaxLength(4096);
                Property(p => p.FullDescription).IsRequired().HasMaxLength(4096 * 4);
            }
        }
    }
}

Dan/Models/Catalog/ProductImageEntity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Web;

namespace Dan.Models.Catalog
{
    public class ProductImageEntity
    {
        public long ImageId { get; set; }
        public long ProductId { get; set; }
        public virtual ProductEntity ProductEntity { get; set; }

        //===============================================================
        public class Configuration : EntityTypeConfiguration<ProductImageEntity>
        {
            public Configuration()
            {
                ToTable("catalog.ProductImageEntity");
                HasKey(p => p.ImageId).Property(p => p.ImageId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            }
        }
    }
}

Dan/Models/Catalog/TemplateParamEnity.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Web;

namespace Dan.Models.Catalog
{
    public class TemplateParamEnity
    {
        public long EntityId { get; set; }
        public string Name { get; set; }
        //public bool DisplayAsFilter { get; set; }

        public class Configuration : EntityTypeConfiguration<TemplateParamEnity>
        {
            public Configuration()
            {
                HasKey(i => i.EntityId);
                ToTable("catalog.TemplateParamEnity");

                //=================================================================
                Property(p => p.Name).IsRequired().HasMaxLength(64);
            }
        }
    }
}

Dan/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Dan.Areas.Admin.Infrastuctures;
using Dan.Infrastructures.Controllers;
using Dan.Infrastructures.Repository;
using Dan.Infrastructures.Session;
using Dan.Models;
using Dan.Models.Common;
using Dan.Models.Order;
using Dan.Models.Tradecart;
using Dan.View.Cart;

namespace Dan.Controllers
{
    public class CartController : DefaultController
    {
        public static readonly NumberFormatInfo CurrencyFormat =  new NumberFormatInfo
        {
            NumberGroupSeparator = " "
        };

        [HttpGet]
        public ActionResult Index()
        {
            //-------------------------------------------------------------------
            var products = TradecartRepository.TakeEntities(SessionId, UserId).ToList().AsView();

            //-------------------------------------------------------------------
            var amount = TradecartRepository.CountEntities(SessionId, UserId, false);
            var cost = TradecartRepository.Sum(SessionId, UserId);

            Session["CartAmount"] = amount;
            Session["CartCost"] = cost;



            //-------------------------------------------------------------------
            var view = new TradecartOrderView
            {
                Products = products,
                Price = products.Sum(p => p.Amount * p.Cost),
                Weight = products.Sum(p => p.Amount * p.Product.Dimensions.Weight),
            };

            //-------------------------------------------------------------------
            return View(view);
        }

        [HttpGet]
        public ActionResult ConfirmOrder()
        {
            //-------------------------------------------------------------------
            var products = TradecartRepository.TakeEntities(SessionId, UserId).ToList().AsView();

            //-------------------------------------------------------------------
            var view = new TradecartConfirmOrder
            {
                Products = products,
                Price = products.Sum(p => p.Amount * p.Cost),
                Weight = products.Sum(p => p.Amount * p.Product.Dimensions.Weight),
                Address = UserManager.Users.SingleOrDefault(p => p.Id == UserId)?.Address?.AsShortView(),
            };


            //-------------------------------------------------------------------
            return View(view);
        }

        [HttpPost]
        public ActionResult ConfirmOrder(TradecartConfirmOrder view)
        {
            //-------------------------------------------------------------------
            var products = TradecartRepository.TakeEntities(SessionId, UserId).ToList();

            //-------------------------------------------------------------------
            if (view.TermsofService == false)
            {

                ModelState.AddModelError(nameof(view.TermsofService), "Вы не дали согласие на обработку персональных данных");
                view.Products = products.AsView();
                view.Price = view.Products.Sum(p => p.Amount * p.Cost);
                view.Weight = view.Products.Sum(p => p.Amount * p.Product.Dimensions.Weight);
                return View(view);
            }

            //-------------------------------------------------------------------
            var email = view.Address.Email.ToLower().Trim();
            var phone = view.Address.PhoneNumber.Trim();

            //-------------------------------------------------------------------
            var password = Membership.GeneratePassword(8, 1);
            var user = Context.Users.FirstOrDefault(p => p.Email == email || p.PhoneNumber == phone);
            try
            {
                if (user == null)
                {
                    Task.Run(async () =>
                        {
                            await CreateUserAccount(new RegisterViewModel
                            {
                                Email = email,
                                Password = password,
                                ConfirmPassword = password
                            }, phone);
                        })
                        .Wait();
                    user = Context.Users.FirstOrDefault(p => p.Email == email);
                    user.Address = new CustomerAddressEntity
                    {
                        Address = view.Address.Address,
                        City = view.Address.City,
                        CreatedDate = DateTime.UtcNow,
                        Email = view.Address.Email,
                        FirstName = view.Address.FirstName,
                        LastName = view.Address.LastName,
                        PhoneNumber = view.Address.PhoneNumber,
                        MiddleName = view.Address.MiddleName,
                        StateProvince = view.Address.StateProvince,
                        ZipPostalCode = view.Address.ZipPostalCode
                    };
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }

            //----------------------------------------------------------------------------------
            CustomerKey.UserId = user?.Id;

            //----------------------------------------------------------------------------------
            var address = UserManager.Users.Single(p => p.Id == UserId).Address;

            //----------------------------------------------------------------------------------
            var order = OrderRepository.CreateOrder(products, CustomerKey, address,
                view.Delivery, Request.UserAgent, GetIpAddress(HttpContext));
            OrderRepository.SaveChanges();

            //-------------------------------------------------------------------
            OrderRepository.SendCreateMessage(order);

            //----------------------------------------------------------------------------------
            TradecartRepository.Model.RemoveRange(products);
            TradecartRepository.SaveChanges();

            //----------------------------------------------------------------------------------
            Session["CartAmount"] = 0;
            Session["CartAmount"] = 0;
            Session["CartWish"] = OrderRepository.TakeCount(CustomerKey);

            //----------------------------------------------------------------------------------
            return RedirectToAction("Details", "Order", new {id = order.EntityId});
        }

        [HttpPost]
        public ActionResult Create(long id, short count = 1)
        {
            CreateAjax(id, count);
            return RedirectToAction("Product", "Catalog", new {id});
        }

        [HttpPost]
        public ActionResult CreateAjax(long id, short count = 1)
        {
            //====================================================================
            var entity = TradecartRepository.Context.ProductEntities.SingleOrDefault(p => p.EntityId == id && p.Deleted == false);
            if (entity == null)
            {
                return HttpNotFound();
            }

            //-------------------------------------------------------------------
            TradecartRepository.AddEntity(entity, SessionId, UserId, count);

            //-------------------------------------------------------------------
            var amount = TradecartRepository.CountEntities(SessionId, UserId, false);
            var cost = TradecartRepository.Sum(SessionId, UserId);

            Session["CartAmount"] = amount;
            Session["CartCost"] = cost;

            //-------------------------------------------------------------------
            return Json(new
            {
                cart = new
                {
                    amount,
                    cost
                },
                product = new
                {
                    id = entity.EntityId,
                    name = entity.Name
                }
            });
            
        }
    }
}

Dan/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Dan.Infrastructures.Controllers;
using Dan.Infrastructures.Repository;
using Dan.Models;
using Dan.Models.Catalog;
using Dan.Models.Image;
using Dan.View.Category;
using Dan.View.Filter;
using Dan.View.Product;
using Dan.View.Shared.Navigation;

namespace Dan.Controllers
{
    public class CatalogController : DefaultController
    {
        [HttpGet]
        public ActionResult Index()
        {
            using (var r = new CategoryRepository())
            {
                return View(r.TakeEntities(null, true).ToList().AsShortView());
            }
        }

        [HttpGet]
        public ActionResult Product(long? id)
        {
            using (var r1 = new ProductRepository())
            {
                //==============================================
                if (id == null)
                {
                    HttpContext.Response.StatusCode = 404;
                    return RedirectToAction("Index");
                }

                //==============================================
                var product = r1.TakeEntity(id.Value);
                if (product == null || product.Deleted)
                {
                    HttpContext.Response.StatusCode = 404;
                    return RedirectToAction("Index");
                }

                //==============================================
                return View(product.AsLargeView());
            }
        }


        public class FilterKeyValue
        {
            public long Key { get; set; }
            public ICollection<long> Value { get; set; }
        }

        [HttpGet]
        public ActionResult Category(long? id
            , string query = null
            , decimal? weightMin = null
            , decimal? weightMax = null
            , decimal? costMin = null
            , decimal? costMax = null
            , ProductOrderMethod? order = null
            , ICollection<long> filter = null
            , bool seed = false
            , int items = 0
            , int page = 1)
        {
            //if (seed) CategorySeed2(id.Value);
            using (var r1 = new ProductRepository())
            {
                using (var r2 = new CategoryRepository(r1.Context))
                {
                    //==============================================
                    if (id == null)
                    {
                        HttpContext.Response.StatusCode = 404;
                        return RedirectToAction("Index");
                    }

                    //==============================================
                    var category = r2.TakeEntity(id.Value);
                    if (category == null || category.Deleted)
                    {
                        HttpContext.Response.StatusCode = 404;
                        return RedirectToAction("Index");
                    }

                    //==============================================
                    ViewBag.Title = category.Name;

                    //==============================================
                    var products = r1.TakeEntities(id, order, true);
                    if (string.IsNullOrWhiteSpace(query) == false && query.Length >= 4)
                    {
                        products = products.Where(p => p.Name.Contains(query) || p.FullDescription.Contains(query));
                    }

                    if (costMin != null) products = products.Where(p => p.Price.Price >= costMin);
                    if (costMax != null) products = products.Where(p => p.Price.Price <= costMax);


                    //==============================================
                    var navigation = new PageNavigationView<ProductEntity, CatalogProductShortView>(products, x => x.AsShortView(), page, items);
                    
                    //==============================================
                    var view = category.AsLargeView(category, false, navigation);

                    //==============================================
                    view.IsSearchView |= string.IsNullOrWhiteSpace(query) == false && query.Length >= 4;
                    view.IsSearchView |= weightMin != null;
                    view.IsSearchView |= weightMax != null;
                    view.IsSearchView |= costMin != null;
                    view.IsSearchView |= costMax != null;
                    view.IsSearchView |= filter != null;

                    //==============================================
                    //if (filter != null)
                    //{
                    //    products = products.Where(p => p.ParamEntities.Any(pp => filter.Contains(pp.EntityId)));
                    //}

                    //==============================================
                    var @params = products.SelectMany(p => p.ParamEntities).GroupBy(p => p.ParamEnity, p => p).ToArray();
                    view.Filters = @params.Select(p => new FilterParamView
                    {
                        EntityId = p.Key.EntityId,
                        Name = p.Key.Name,
                        Values = p.Select(v => new FilterParamValueView
                        {
                            Name = v.Value,
                            EntityId = v.EntityId
                        }).ToList()
                    }).ToArray().Take(10).ToArray();

                    //==============================================
                    if (products.Any())
                    {
                        view.WeightSeed = new CatalogSliderFilter(products.Min(p => p.Dimensions.Weight), products.Max(p => p.Dimensions.Weight));
                        view.WeightFilter = new CatalogSliderFilter(weightMin, weightMax);

                        view.CostSeed = new CatalogSliderFilter(products.Min(p => p.Price.Price), products.Max(p => p.Price.Price));
                        view.CostFilter = new CatalogSliderFilter(costMin, costMax);
                    }
                    
                    //==============================================
                    return View("CategoryIndex", view);
                }
            }
        }



    }
}

Dan/Views/Catalog/CategoryDetail.cshtml
@using Dan.Models.Catalog
@model Dan.View.Category.CatalogCategoryLargeView


<div class="col-md-3" style="margin-bottom: 20px;">
    <div class="Title">
        <h2 style="background-color: #313f8f;; color: white; margin: 0; height: 60px; vertical-align: middle; line-height: 60px; text-align: center; font-size: 18px;">
            @Html.ActionLink(Model.Name, "Category", new { id = Model.EntityId }, new { style = "color: white;" })
        </h2>
    </div>

    @if (Model.DisplayMethod.HasFlag(CatalogDisplayMethod.LargeCategory))
    {
        <div class="Image">

        </div>
        <div class="Footer" style="background-color: #95a5a6; padding: 15px; height: 160px;">
            <ul>
                @foreach (var c in Model.CategoryViews)
                {
                    <li>
                        @Html.ActionLink(c.Name, "Category", new {id = c.EntityId}, new {style = "color: white;"})
                    </li>
                }
            </ul>
        </div>
    }
    
</div>

Dan/Views/Catalog/CategoryFilterPrice.cshtml
@model Dan.View.Category.CatalogCategoryLargeView

<style>
    .panel-group .panel {
        border-radius: 0;
        box-shadow: none;
        border-color: #EEEEEE;
    }

    .panel-default > .panel-heading {
        padding: 0;
        border-radius: 0;
        color: #212121;
        background-color: #FAFAFA;
        border-color: #EEEEEE;
    }

    .panel-title {
        font-size: 14px;
    }

        .panel-title > a {
            display: block;
            padding: 15px;
            text-decoration: none;
        }

    .more-less {
        float: right;
        color: #212121;
    }

    .panel-default > .panel-heading + .panel-collapse > .panel-body {
        border-top-color: #EEEEEE;
    }

    .panel-group .panel + .panel {
        margin-top: 0;
    }
</style>

<script>
    function toggleIcon(e) {
        $(e.target)
            .prev('.panel-heading')
            .find(".more-less")
            .toggleClass('glyphicon-plus glyphicon-minus');
    }
    $('.panel-group').on('hidden.bs.collapse', toggleIcon);
    $('.panel-group').on('shown.bs.collapse', toggleIcon);
</script>

<div class="Block">
    <div class="Title">
        <h2 style="background-color: #313f8f;;
    color: white;
    margin: 0;
    height: 60px;
    vertical-align: middle;
    line-height: 60px;
    text-align: center;">
            Поиск
        </h2>
    </div>
    <div class="Footer" style="background-color: #4050af; height: 170px;">

        @using (Html.BeginForm("Category", "Catalog", null, FormMethod.Get, null))
        {
            @Html.ValidationSummary(true, "", new {@class = "text-danger"})

            <div class="input-group">
                <input name="query" type="text" class="form-control" style="border-radius: 0;" placeholder="Search for...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit" style="border-radius: 0;">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div>
            <!-- /input-group -->

            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                <i class="more-less glyphicon glyphicon-plus"></i>
                                Стоимость
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">
                            <input name="costMin" type="number" class="form-control" style="border-radius: 0;" value="@Model.CostFilter.Min" placeholder="@Model.CostSeed.Min">
                            <input name="costMax" type="number" class="form-control" style="border-radius: 0;" value="@Model.CostFilter.Max" placeholder="@Model.CostSeed.Max">
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingThour">
                        <h4 class="panel-title">
                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThour" aria-expanded="false" aria-controls="collapseThree">
                                <i class="more-less glyphicon glyphicon-plus"></i>
                                Вес
                            </a>
                        </h4>
                    </div>
                    <div id="collapseThour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThour">
                        <div class="panel-body">
                            <input name="weightMin" type="number" class="form-control" style="border-radius: 0;" value="@Model.WeightFilter.Min" placeholder="@Model.WeightSeed.Min">
                            <input name="weightMax" type="number" class="form-control" style="border-radius: 0;" value="@Model.WeightFilter.Max" placeholder="@Model.WeightSeed.Max">
                        </div>
                    </div>
                </div>
                
                @*

    @{
        var itter = 0;
    }

    @foreach (var f in Model.Filters.Take(1))
    {
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading@(f.EntityId)">
                <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse@(f.EntityId)" aria-expanded="false" aria-controls="collapseThree">
                        <i class="more-less glyphicon glyphicon-plus"></i>
                        @f.Name
                    </a>
                </h4>
            </div>
            <div id="collapse@(f.EntityId)" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading@(f.EntityId)">
                <div class="panel-body">
                    @foreach (var v in f.Values)
                    {
                        <div>
                            <input type="checkbox" name="filter[@itter]" value="@v.EntityId" />
                            @Html.Label($"filter[{itter}]", v.Name)
                            @{ itter++; }


                        </div>
                    }
                </div>
            </div>
        </div>
    }
                *@

            </div>
            <!-- panel-group -->
        }
    </div>
</div>

Dan/Views/Catalog/CategoryProduct.cshtml
@model Dan.View.Product.CatalogProductShortView

<div class="col-md-3" style="margin-bottom: 25px;">
    <div style="border: 1px solid #e1e1e1;">
        <div class="Image" style="height: 250px;">
            <a href=@Url.Action("Product", new {id = Model.EntityId})>
                <img style="width: 100%; height: 100%;" src="@Model.Image.FilePath"/>
            </a>
        </div>
        <div class="Title">
            <h2 style="font-size: 14px;
    font-weight: 700;
    line-height: 19px;
    font-family: arial; height: 50px;     padding-left: 10px;     padding-top: 5px;
    padding-right: 10px;     background-color: #4050af; margin: 0;">
                @Html.ActionLink(Model.Name, "Product", new {id = Model.EntityId}, new {style="color: white;"})
            </h2>
        </div>

        <div class="Footer">
            <div style="float: left; background-color: #313f8f;;  bottom: 0;
    height: 45px;
    color: white;
    font-size: 16px;
    font-weight: 700;
    text-align: center; vertical-align: middle; line-height: 45px; width: 40%;">
                @Model.Price.Price <span class="glyphicon glyphicon-ruble" style="font-size: 13px; font-weight: 100;"></span>
            </div>

            <div style="background-color: #4050af; float: left; width: 60%;
    bottom: 0;
    height: 45px;
    color: white;
    font-size: 16px;
    font-weight: 700;
    text-align: center; vertical-align: middle; line-height: 45px">
                @using (Ajax.BeginForm("Create", "Cart", new AjaxOptions
                {
                    Url = Url.Action("CreateAjax", "Cart"),
                    OnSuccess = "OnSuccessAddProductToCart",
                    HttpMethod = "POST"
                }))
                {
                    <input id="id" name="id" style="display: none;" type="text" value="@Model.EntityId">
                    <input type="submit" value="В корзину" style="background-color: transparent;border: none;width: 100%;" />
                }

            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

Dan/Views/Catalog/CategorySearchBox.cshtml
@using (Html.BeginForm("Search", "Catalog", FormMethod.Get, new { @class = "form-horizontal", role = "form" }))
            {
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="input-group">
        <input id="id" type="text" class="form-control" style="border-radius: 0;" placeholder="Search for...">
        <span class="input-group-btn">
            <button class="btn btn-default" type="submit" style="border-radius: 0;">
                <span class="glyphicon glyphicon-search"></span>
            </button>
        </span>
    </div><!-- /input-group -->
}

Dan/Views/Catalog/Product.cshtml
@using System.Web.Mvc.Ajax
@model Dan.View.Product.CatalogProductLargeView

@{
    ViewBag.Title = "Product";
}

<style>
    .spinner {
        width: 100px;
    }

        .spinner input {
            text-align: right;
        }

    .input-group-btn-vertical {
        position: relative;
        white-space: nowrap;
        width: 1%;
        vertical-align: middle;
        display: table-cell;
    }

        .input-group-btn-vertical > .btn {
            display: block;
            float: none;
            width: 100%;
            max-width: 100%;
            padding: 8px;
            margin-left: -1px;
            position: relative;
            border-radius: 0;
        }

            .input-group-btn-vertical > .btn:first-child {
                border-top-right-radius: 4px;
            }

            .input-group-btn-vertical > .btn:last-child {
                margin-top: -2px;
                border-bottom-right-radius: 4px;
            }

        .input-group-btn-vertical i {
            position: absolute;
            top: 0;
            left: 4px;
        }


</style>

<script>
    (function ($) {
        $('.spinner .btn:first-of-type').on('click', function () {
            $('.spinner input').val(parseInt($('.spinner input').val(), 10) + 1);
        });
        $('.spinner .btn:last-of-type').on('click', function () {
            $('.spinner input').val(parseInt($('.spinner input').val(), 10) - 1);
        });
    })(jQuery);
</script>

<script>
    $(document).ready(function () {
        $("#AddToCart").click(function () {
            $('#ProductForm').get(0).submit();
        });
    });
</script>


<div class="row">
    <div class="container">
        <div class="col-md-12">
            <div style="color:white; background-color: #313f8f; height: 50px;">
                <h1 style="float: left; margin: 0; padding-top: 5px; padding-left: 25px;">
                    @Model.Name
                </h1>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="col-md-6">
            <div class="Param">
                <span class="Key">Артикул</span>
                <span class="Value">CE8139</span>
            </div>

            <div class="Param">
                <span class="Key">Бренд</span>
                <span class="Value">Adidas</span>
            </div>

            <div class="Param">
                <span class="Key">Цвет</span>
                <span class="Value">Белый/серый/черный/золотистый</span>
            </div>

            <div class="Param">
                <span class="Key">Размер</span>
                <span class="Value">1</span>
            </div>
            
            
            @foreach (var param in Model.Params)
            {
                <div class="Param">
                    <span class="Key">@param.Name</span>
                    <span class="Value">@param.Value</span>
                </div>
            }


            <div class="form-group">


                @using (Ajax.BeginForm("Create", "Cart", new AjaxOptions
                {
                    Url = Url.Action("CreateAjax", "Cart"),
                    OnSuccess = "OnSuccessAddProductToCart",
                    HttpMethod = "POST"
                }))
                {

                    <div class="Param" style="display: inline-block; width: 150px; padding-right: 0; min-width: 150px;">
                        <span class="Key">Кол-во</span>
                        
                        @Html.TextBox("id", Model.EntityId, new { style = "display: none;" })
                        
                        @Html.TextBox("amount", 1, new { @class = "Value Quantity" })
                    </div>

                    <button type="submit" value="В корзину" class="AddToCart">
                        Добавить в корзину
                    </button>

                    <div class="Price">
                        @Model.Price.Price руб
                    </div>

                }
            </div>

            @Html.Raw(Model.Description)
        </div>
        <div class="col-md-6">
            <img src="@Model.Image.FilePath" style="width: 100%; background-color: white;padding: 15px;"/>
        </div>

        <div class="clearfix"></div>
    </div>
</div>